// <auto-generated />
using System;
using DataAccessLayer.Concrate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240208214334_surucuTanimlar")]
    partial class surucuTanimlar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrate.AdresOzellikTanimlama", b =>
                {
                    b.Property<int>("Adres_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Adres_ID"));

                    b.Property<string>("ILCE_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IL_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posta_Kodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Adres_ID");

                    b.ToTable("AdresOzellikTanimlama");
                });

            modelBuilder.Entity("EntityLayer.Concrate.AkuTipi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("AkuTipi");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Arac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AkuAdet")
                        .HasColumnType("int");

                    b.Property<string>("AkuAmperBirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AkuTipID")
                        .HasColumnType("int");

                    b.Property<int?>("AracTipID")
                        .HasColumnType("int");

                    b.Property<int?>("AracTurID")
                        .HasColumnType("int");

                    b.Property<float?>("AzamiYukluAgirlik")
                        .HasColumnType("real");

                    b.Property<string>("BakimPeriyodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("BosAgirlik")
                        .HasColumnType("real");

                    b.Property<float?>("BunyeCikisFiyat")
                        .HasColumnType("real");

                    b.Property<string>("BunyeCikisNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BunyeCikisTarih")
                        .HasColumnType("datetime2");

                    b.Property<float?>("BunyeGirisFiyat")
                        .HasColumnType("real");

                    b.Property<string>("BunyeGirisNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BunyeGirisTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepoSensorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DuzenleyenID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Ekipman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EuroPalet")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int?>("GarantiBaslangicKm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GarantiBaslangicTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GarantiBitisKm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GarantiBitisTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GarantiKmLimit")
                        .HasColumnType("int");

                    b.Property<int?>("Goz1")
                        .HasColumnType("int");

                    b.Property<int?>("Goz2")
                        .HasColumnType("int");

                    b.Property<int?>("Goz3")
                        .HasColumnType("int");

                    b.Property<int?>("Goz4")
                        .HasColumnType("int");

                    b.Property<int?>("Goz5")
                        .HasColumnType("int");

                    b.Property<int?>("Goz6")
                        .HasColumnType("int");

                    b.Property<float?>("GresYagKg")
                        .HasColumnType("real");

                    b.Property<string>("GresYagTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupID")
                        .HasColumnType("int");

                    b.Property<string>("HGS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HavaFiltreAdet")
                        .HasColumnType("int");

                    b.Property<int?>("HavaFiltreKm")
                        .HasColumnType("int");

                    b.Property<string>("HidrolikYagListesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("HidrolikYagPeriyot")
                        .HasColumnType("real");

                    b.Property<string>("HidrolikYagTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IseBaslamaNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IseBaslamaSuresi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IseBaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<float?>("IstiapHaddi")
                        .HasColumnType("real");

                    b.Property<float?>("KasaBoy")
                        .HasColumnType("real");

                    b.Property<float?>("KasaEn")
                        .HasColumnType("real");

                    b.Property<float?>("KasaYukseklik")
                        .HasColumnType("real");

                    b.Property<int?>("KiralamaSuresi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KiralamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<float?>("KiralamaTutari")
                        .HasColumnType("real");

                    b.Property<string>("LastikTip1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastikTip2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastikTip3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarkaID")
                        .HasColumnType("int");

                    b.Property<int?>("MazotFiltre")
                        .HasColumnType("int");

                    b.Property<int?>("MazotFiltreAdet")
                        .HasColumnType("int");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.Property<string>("MotorGucu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorSeriNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorYagListesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MotorYagPeriyot")
                        .HasColumnType("real");

                    b.Property<string>("MotorYagTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorluAracSeriNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OlusturanId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuhsatSahibi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RuhsatSonKullanma")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SahiplikID")
                        .HasColumnType("int");

                    b.Property<string>("SaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SirketID")
                        .HasColumnType("int");

                    b.Property<string>("TTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakografSeriNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaksimetreSeriNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TescilSeriNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TescilSiraNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TescilTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrafigeCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerildigiIlID")
                        .HasColumnType("int");

                    b.Property<int?>("VerildigiIlceID")
                        .HasColumnType("int");

                    b.Property<int?>("YagFiltre")
                        .HasColumnType("int");

                    b.Property<int?>("YagFiltreAdet")
                        .HasColumnType("int");

                    b.Property<int?>("YakitDepo")
                        .HasColumnType("int");

                    b.Property<int?>("YakitSarfiyat")
                        .HasColumnType("int");

                    b.Property<int?>("YakitTipiID")
                        .HasColumnType("int");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Arac");
                });

            modelBuilder.Entity("EntityLayer.Concrate.AracTip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracTurID")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("AracTip");
                });

            modelBuilder.Entity("EntityLayer.Concrate.AracTur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("AracTur");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Durumlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Durumlar");
                });

            modelBuilder.Entity("EntityLayer.Concrate.EhliyetSinifi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("EhliyetSinifi");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Firma", b =>
                {
                    b.Property<int>("Firma_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Firma_ID"));

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("EkleyenKullanici_ID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaModul_ID")
                        .HasColumnType("int");

                    b.Property<string>("Firma_Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Firma_AdresILCE_ID")
                        .HasColumnType("int");

                    b.Property<int>("Firma_AdresIL_ID")
                        .HasColumnType("int");

                    b.Property<string>("Firma_CepTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Firma_Durum")
                        .HasColumnType("tinyint");

                    b.Property<string>("Firma_TCNO_VKNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Firma_Tipi")
                        .HasColumnType("int");

                    b.Property<string>("Firma_Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma_VergiDairesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma_WebSitesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma_YetkiliAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma_YetkiliEposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma_YetkiliSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Firma_ID");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("EntityLayer.Concrate.FirmaModul", b =>
                {
                    b.Property<int>("FirmaModul_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaModul_ID"));

                    b.Property<int>("Firma_ID")
                        .HasColumnType("int");

                    b.Property<int>("Modul_ID")
                        .HasColumnType("int");

                    b.HasKey("FirmaModul_ID");

                    b.ToTable("FirmaModul");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Grup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Grup");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Izinler", b =>
                {
                    b.Property<int>("Izin_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Izin_ID"));

                    b.Property<byte>("Durum")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("EkleyenKullanici_ID")
                        .HasColumnType("int");

                    b.Property<string>("Izin_Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Izin_Ekleme_Sil")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Izin_Guncelleme")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Izin_Listeleme")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Izin_ID");

                    b.ToTable("Izinler");
                });

            modelBuilder.Entity("EntityLayer.Concrate.KullaniciGrubu", b =>
                {
                    b.Property<int>("KullaniciGrup_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciGrup_ID"));

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("EkleyenKullanici_ID")
                        .HasColumnType("int");

                    b.Property<int>("Firma_ID")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciGrup_Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("KullaniciGrup_Durum")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("KullaniciGrup_ID");

                    b.ToTable("KullaniciGrubu");
                });

            modelBuilder.Entity("EntityLayer.Concrate.KullaniciYetkiler", b =>
                {
                    b.Property<int>("Yetki_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Yetki_ID"));

                    b.Property<int>("FirmaModul_ID")
                        .HasColumnType("int");

                    b.Property<int>("Izinler_ID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciGruplari_ID")
                        .HasColumnType("int");

                    b.HasKey("Yetki_ID");

                    b.ToTable("KullaniciYetkiler");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Kullanicilar", b =>
                {
                    b.Property<int>("Kullanici_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kullanici_ID"));

                    b.Property<int>("EkleyenKullanici_ID")
                        .HasColumnType("int");

                    b.Property<int>("Firma_ID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciGrup_ID")
                        .HasColumnType("int");

                    b.Property<bool>("Kullanici_Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Kullanici_DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kullanici_Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kullanici_Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Kullanici_OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kullanici_Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kullanici_Soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kullanici_Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kullanici_ID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EntityLayer.Concrate.LastikTipi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("LastikTipi");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Marka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Marka");
                });

            modelBuilder.Entity("EntityLayer.Concrate.MasrafTipi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MasrafTipi");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("MarkaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Moduller", b =>
                {
                    b.Property<int>("Modul_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Modul_ID"));

                    b.Property<string>("Modul_Adi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Modul_ID");

                    b.ToTable("Moduller");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Sahiplik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Sahiplik");
                });

            modelBuilder.Entity("EntityLayer.Concrate.SurucuCikisNedeni", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("SurucuCikisNedeni");
                });

            modelBuilder.Entity("EntityLayer.Concrate.SurucuPozisyon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("SurucuPozisyon");
                });

            modelBuilder.Entity("EntityLayer.Concrate.YakitTipi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuzenleyenID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("YakitTipi");
                });
#pragma warning restore 612, 618
        }
    }
}
